// @ts-nocheck -- skip type checking
import * as docs_13 from "../content/docs/backends/metal.mdx?collection=docs&hash=1767447348489"
import * as docs_12 from "../content/docs/backends/cuda.mdx?collection=docs&hash=1767447348489"
import * as docs_11 from "../content/docs/backends/cpu.mdx?collection=docs&hash=1767447348489"
import * as docs_10 from "../content/docs/integration/go.mdx?collection=docs&hash=1767447348489"
import * as docs_9 from "../content/docs/integration/cmake.mdx?collection=docs&hash=1767447348489"
import * as docs_8 from "../content/docs/concepts/streams.mdx?collection=docs&hash=1767447348489"
import * as docs_7 from "../content/docs/concepts/memory.mdx?collection=docs&hash=1767447348489"
import * as docs_6 from "../content/docs/concepts/arrays.mdx?collection=docs&hash=1767447348489"
import * as docs_5 from "../content/docs/api/ops.mdx?collection=docs&hash=1767447348489"
import * as docs_4 from "../content/docs/api/linalg.mdx?collection=docs&hash=1767447348489"
import * as docs_3 from "../content/docs/api/fft.mdx?collection=docs&hash=1767447348489"
import * as docs_2 from "../content/docs/api/creation.mdx?collection=docs&hash=1767447348489"
import * as docs_1 from "../content/docs/installation.mdx?collection=docs&hash=1767447348489"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1767447348489"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"installation.mdx","fullPath":"content/docs/installation.mdx"}, data: docs_1 }, { info: {"path":"api/creation.mdx","fullPath":"content/docs/api/creation.mdx"}, data: docs_2 }, { info: {"path":"api/fft.mdx","fullPath":"content/docs/api/fft.mdx"}, data: docs_3 }, { info: {"path":"api/linalg.mdx","fullPath":"content/docs/api/linalg.mdx"}, data: docs_4 }, { info: {"path":"api/ops.mdx","fullPath":"content/docs/api/ops.mdx"}, data: docs_5 }, { info: {"path":"concepts/arrays.mdx","fullPath":"content/docs/concepts/arrays.mdx"}, data: docs_6 }, { info: {"path":"concepts/memory.mdx","fullPath":"content/docs/concepts/memory.mdx"}, data: docs_7 }, { info: {"path":"concepts/streams.mdx","fullPath":"content/docs/concepts/streams.mdx"}, data: docs_8 }, { info: {"path":"integration/cmake.mdx","fullPath":"content/docs/integration/cmake.mdx"}, data: docs_9 }, { info: {"path":"integration/go.mdx","fullPath":"content/docs/integration/go.mdx"}, data: docs_10 }, { info: {"path":"backends/cpu.mdx","fullPath":"content/docs/backends/cpu.mdx"}, data: docs_11 }, { info: {"path":"backends/cuda.mdx","fullPath":"content/docs/backends/cuda.mdx"}, data: docs_12 }, { info: {"path":"backends/metal.mdx","fullPath":"content/docs/backends/metal.mdx"}, data: docs_13 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"title":"Lux GPU Documentation","pages":["index","installation","---Concepts---","concepts/arrays","concepts/memory","concepts/streams","---API Reference---","api/creation","api/ops","api/linalg","api/fft","---Backends---","backends/metal","backends/cuda","backends/cpu","---Integration---","integration/cmake","integration/go"]}}])