# Copyright (c) 2024-2026 Lux Industries Inc.
# SPDX-License-Identifier: BSD-3-Clause-Eco
#
# EmbedKernels.cmake - Generate C++ headers with embedded GPU kernel sources
#
# Functions:
#   lux_embed_kernels(TARGET BACKEND KERNEL_DIR OUTPUT_DIR)
#     - Scans KERNEL_DIR for kernel files
#     - Generates embedded source headers
#     - Compiles to binary formats where applicable
#
# Usage:
#   include(cmake/EmbedKernels.cmake)
#   lux_embed_kernels(luxgpu_backend_metal metal ${CMAKE_SOURCE_DIR}/kernels/metal)

# Find all kernel files for a backend
function(lux_find_kernels BACKEND KERNEL_DIR OUT_VAR)
    if(BACKEND STREQUAL "metal")
        file(GLOB_RECURSE kernels "${KERNEL_DIR}/**/*.metal" "${KERNEL_DIR}/*.metal")
    elseif(BACKEND STREQUAL "cuda")
        file(GLOB_RECURSE kernels "${KERNEL_DIR}/**/*.cu" "${KERNEL_DIR}/*.cu")
    elseif(BACKEND STREQUAL "webgpu")
        file(GLOB_RECURSE kernels "${KERNEL_DIR}/**/*.wgsl" "${KERNEL_DIR}/*.wgsl")
    else()
        set(kernels "")
    endif()
    set(${OUT_VAR} ${kernels} PARENT_SCOPE)
endfunction()

# Generate C-string-safe escaped source from file
function(lux_escape_source INPUT_FILE OUTPUT_VAR)
    file(READ "${INPUT_FILE}" content)
    # Escape backslashes, then double quotes, then newlines
    string(REPLACE "\\" "\\\\" content "${content}")
    string(REPLACE "\"" "\\\"" content "${content}")
    string(REPLACE "\n" "\\n\"\n\"" content "${content}")
    set(${OUTPUT_VAR} "\"${content}\"" PARENT_SCOPE)
endfunction()

# Generate kernel name from file path
function(lux_kernel_name FILE_PATH KERNEL_DIR OUT_VAR)
    # Get relative path and convert to identifier
    file(RELATIVE_PATH rel_path "${KERNEL_DIR}" "${FILE_PATH}")
    get_filename_component(name_we "${rel_path}" NAME_WE)
    get_filename_component(dir "${rel_path}" DIRECTORY)

    if(dir)
        string(REPLACE "/" "_" dir_id "${dir}")
        set(kernel_name "${dir_id}_${name_we}")
    else()
        set(kernel_name "${name_we}")
    endif()

    # Sanitize: replace non-alphanumeric with underscore
    string(REGEX REPLACE "[^a-zA-Z0-9_]" "_" kernel_name "${kernel_name}")
    set(${OUT_VAR} ${kernel_name} PARENT_SCOPE)
endfunction()

# Main function: embed kernels for a backend
function(lux_embed_kernels TARGET BACKEND KERNEL_DIR)
    set(OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated/${BACKEND}")
    file(MAKE_DIRECTORY "${OUTPUT_DIR}")

    # Find all kernels
    lux_find_kernels(${BACKEND} "${KERNEL_DIR}" KERNEL_FILES)

    if(NOT KERNEL_FILES)
        message(STATUS "No kernel files found for ${BACKEND} in ${KERNEL_DIR}")
        return()
    endif()

    list(LENGTH KERNEL_FILES kernel_count)
    message(STATUS "Embedding ${kernel_count} ${BACKEND} kernels")

    # Generate header for each kernel
    set(ALL_KERNEL_HEADERS "")
    set(REGISTRY_ENTRIES "")

    foreach(kernel_file ${KERNEL_FILES})
        lux_kernel_name("${kernel_file}" "${KERNEL_DIR}" kernel_name)

        set(header_file "${OUTPUT_DIR}/${kernel_name}.h")
        list(APPEND ALL_KERNEL_HEADERS "${header_file}")

        # Add custom command to generate header
        add_custom_command(
            OUTPUT "${header_file}"
            COMMAND ${CMAKE_COMMAND}
                -DINPUT_FILE=${kernel_file}
                -DOUTPUT_FILE=${header_file}
                -DKERNEL_NAME=${kernel_name}
                -DBACKEND=${BACKEND}
                -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/GenerateKernelHeader.cmake
            DEPENDS "${kernel_file}" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/GenerateKernelHeader.cmake"
            COMMENT "Generating embedded kernel: ${kernel_name}"
        )

        # Determine entry point (use kernel name for simple cases)
        get_filename_component(entry_point "${kernel_file}" NAME_WE)

        # Determine language enum
        if(BACKEND STREQUAL "metal")
            set(lang_enum "LUX_KERNEL_LANG_METAL")
        elseif(BACKEND STREQUAL "cuda")
            set(lang_enum "LUX_KERNEL_LANG_CUDA")
        elseif(BACKEND STREQUAL "webgpu")
            set(lang_enum "LUX_KERNEL_LANG_WGSL")
        endif()

        # Build registry entry
        string(APPEND REGISTRY_ENTRIES "    { \"${kernel_name}\", \"${entry_point}\", ${lang_enum}, lux_kernel_${kernel_name}_source, lux_kernel_${kernel_name}_source_len, nullptr, 0 },\n")
    endforeach()

    # Generate registry source file
    set(registry_file "${OUTPUT_DIR}/${BACKEND}_registry.cpp")

    # Build includes
    set(INCLUDES_CONTENT "")
    foreach(header ${ALL_KERNEL_HEADERS})
        get_filename_component(header_name "${header}" NAME)
        string(APPEND INCLUDES_CONTENT "#include \"${header_name}\"\n")
    endforeach()

    # Generate registry file content
    file(WRITE "${registry_file}.in" "
// Auto-generated ${BACKEND} kernel registry
// DO NOT EDIT - Generated by EmbedKernels.cmake

#include \"lux/gpu/kernel_loader.h\"
${INCLUDES_CONTENT}

namespace {

static const LuxEmbeddedKernel ${BACKEND}_kernels[] = {
${REGISTRY_ENTRIES}};

static const LuxKernelRegistry ${BACKEND}_registry = {
    \"${BACKEND}\",
    ${BACKEND}_kernels,
    sizeof(${BACKEND}_kernels) / sizeof(${BACKEND}_kernels[0])
};

} // namespace

extern \"C\" const LuxKernelRegistry* lux_kernel_registry_${BACKEND}_get(void) {
    return &${BACKEND}_registry;
}
")

    configure_file("${registry_file}.in" "${registry_file}" COPYONLY)

    # Add sources to target
    target_sources(${TARGET} PRIVATE
        ${ALL_KERNEL_HEADERS}
        "${registry_file}"
    )

    target_include_directories(${TARGET} PRIVATE "${OUTPUT_DIR}")

    # Create custom target for kernel headers
    add_custom_target(${TARGET}_kernels DEPENDS ${ALL_KERNEL_HEADERS})
    add_dependencies(${TARGET} ${TARGET}_kernels)
endfunction()

# Compile Metal shaders to metallib
function(lux_compile_metal_shaders TARGET KERNEL_DIR)
    if(NOT APPLE)
        return()
    endif()

    set(OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/metallib")
    file(MAKE_DIRECTORY "${OUTPUT_DIR}")

    file(GLOB_RECURSE METAL_FILES "${KERNEL_DIR}/**/*.metal" "${KERNEL_DIR}/*.metal")

    set(METALLIB_FILES "")

    foreach(metal_file ${METAL_FILES})
        get_filename_component(name_we "${metal_file}" NAME_WE)
        get_filename_component(dir "${metal_file}" DIRECTORY)
        file(RELATIVE_PATH rel_dir "${KERNEL_DIR}" "${dir}")

        if(rel_dir)
            set(output_name "${rel_dir}_${name_we}")
            string(REPLACE "/" "_" output_name "${output_name}")
        else()
            set(output_name "${name_we}")
        endif()

        set(air_file "${OUTPUT_DIR}/${output_name}.air")
        set(metallib_file "${OUTPUT_DIR}/${output_name}.metallib")

        # Compile .metal -> .air
        add_custom_command(
            OUTPUT "${air_file}"
            COMMAND xcrun -sdk macosx metal -c "${metal_file}" -o "${air_file}"
            DEPENDS "${metal_file}"
            COMMENT "Compiling Metal shader: ${name_we}"
            VERBATIM
        )

        # Link .air -> .metallib
        add_custom_command(
            OUTPUT "${metallib_file}"
            COMMAND xcrun -sdk macosx metallib "${air_file}" -o "${metallib_file}"
            DEPENDS "${air_file}"
            COMMENT "Linking Metal library: ${name_we}"
            VERBATIM
        )

        list(APPEND METALLIB_FILES "${metallib_file}")
    endforeach()

    # Custom target for all metallibs
    add_custom_target(${TARGET}_metallibs DEPENDS ${METALLIB_FILES})
    add_dependencies(${TARGET} ${TARGET}_metallibs)

    # Store metallib paths for installation
    set_target_properties(${TARGET} PROPERTIES
        LUX_METALLIB_FILES "${METALLIB_FILES}"
        LUX_METALLIB_DIR "${OUTPUT_DIR}"
    )
endfunction()

# Compile CUDA kernels to PTX
function(lux_compile_cuda_ptx TARGET KERNEL_DIR)
    if(NOT CMAKE_CUDA_COMPILER)
        return()
    endif()

    set(OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/ptx")
    file(MAKE_DIRECTORY "${OUTPUT_DIR}")

    file(GLOB_RECURSE CUDA_FILES "${KERNEL_DIR}/**/*.cu" "${KERNEL_DIR}/*.cu")

    set(PTX_FILES "")

    foreach(cuda_file ${CUDA_FILES})
        get_filename_component(name_we "${cuda_file}" NAME_WE)
        get_filename_component(dir "${cuda_file}" DIRECTORY)
        file(RELATIVE_PATH rel_dir "${KERNEL_DIR}" "${dir}")

        if(rel_dir)
            set(output_name "${rel_dir}_${name_we}")
            string(REPLACE "/" "_" output_name "${output_name}")
        else()
            set(output_name "${name_we}")
        endif()

        set(ptx_file "${OUTPUT_DIR}/${output_name}.ptx")

        # Compile .cu -> .ptx
        add_custom_command(
            OUTPUT "${ptx_file}"
            COMMAND ${CMAKE_CUDA_COMPILER}
                -ptx
                -arch=sm_70  # Volta and later
                --std=c++17
                -o "${ptx_file}"
                "${cuda_file}"
            DEPENDS "${cuda_file}"
            COMMENT "Compiling CUDA PTX: ${name_we}"
            VERBATIM
        )

        list(APPEND PTX_FILES "${ptx_file}")
    endforeach()

    # Custom target for all PTX
    add_custom_target(${TARGET}_ptx DEPENDS ${PTX_FILES})
    add_dependencies(${TARGET} ${TARGET}_ptx)

    # Store PTX paths
    set_target_properties(${TARGET} PROPERTIES
        LUX_PTX_FILES "${PTX_FILES}"
        LUX_PTX_DIR "${OUTPUT_DIR}"
    )
endfunction()
