# Copyright (c) 2024-2026 Lux Industries Inc.
# SPDX-License-Identifier: BSD-3-Clause-Eco
#
# GenerateKernelHeader.cmake - Generate C++ header with embedded kernel source
#
# Invoked by EmbedKernels.cmake via add_custom_command
# Variables:
#   INPUT_FILE  - Source kernel file
#   OUTPUT_FILE - Output header file
#   KERNEL_NAME - Kernel identifier
#   BACKEND     - Backend name (metal, cuda, webgpu)

if(NOT INPUT_FILE OR NOT OUTPUT_FILE OR NOT KERNEL_NAME OR NOT BACKEND)
    message(FATAL_ERROR "GenerateKernelHeader: Missing required variables")
endif()

# Read source file
file(READ "${INPUT_FILE}" source_content)

# Get source length before escaping
string(LENGTH "${source_content}" source_len)

# Escape for C string literal
# Order matters: backslash first, then quotes, then special chars
string(REPLACE "\\" "\\\\" source_content "${source_content}")
string(REPLACE "\"" "\\\"" source_content "${source_content}")
string(REPLACE "\t" "\\t" source_content "${source_content}")
string(REPLACE "\n" "\\n" source_content "${source_content}")

# Generate header content
set(header_content "// Auto-generated from ${INPUT_FILE}
// DO NOT EDIT - Generated by GenerateKernelHeader.cmake

#ifndef LUX_KERNEL_${KERNEL_NAME}_H
#define LUX_KERNEL_${KERNEL_NAME}_H

#include <stddef.h>

static const char lux_kernel_${KERNEL_NAME}_source[] =
    \"${source_content}\";

static const size_t lux_kernel_${KERNEL_NAME}_source_len = ${source_len};

#endif // LUX_KERNEL_${KERNEL_NAME}_H
")

# Write header file
file(WRITE "${OUTPUT_FILE}" "${header_content}")

message(STATUS "Generated ${OUTPUT_FILE} (${source_len} bytes)")
